### ISSUE TITLE
Toelichting NEN-3610 

### ISSUE THREAD

**Issue by rcdeboer** [ErfgoedRegistratieStandaard/ers-spec#1]
Opnemen toelichting aansluiting NEN-3610 bij IM_ERS_Object

**Comment by rcdeboer** [comment]
Toelichting opbouw NEN 3610 ID

**Comment by marjoleinsteeman** [comment]
Kunnen we de tekst die uitleg geeft over NEN3610 opnemen in het informatiemodel? Daarmee blijft de opbouw van de hoofdstukken gelijk en kunnen wij de tekst zelf redigeren.

**Comment by rcdeboer** [comment]
De de tekst is nu te bewerken in het bestand [IM_ERS_Object-toelichting.md](https://github.com/ErfgoedRegistratieStandaard/ers-spec/blob/main/OT-IM_ERS_Object-toelichting.md)
