### ISSUE TITLE
aanvullingen cultuurhistorie

### ISSUE THREAD

**Issue by marjoleinsteeman** [ErfgoedRegistratieStandaard/ers-spec#10]
3.2.3.24 redengevendeOmschrijving: graag aanpassen.
**Naam**: toelichtingWaarde
**Definitie**: Een toelichting op de cultuurhistorische waardering en/of de beschermde status van een ErgoedObject.
**Toelichting**:  Deze kan bestaan uit een herhaling, samenvatting van of verwijzing naar de redengevende omschrijving. Of bevat een korte toelichting op waardekenmerken in het algemeen en/of waarderingsuitkomsten.

Kardinaliteit nu: verplicht in combinatie met Mogelijk geen waarde=ja.
Aanpassen naar: optioneel [0..1] en Mogelijk geen waarde is default (nee).

3.2.3.25 beschrijving en 3.4.3.13 beschrijving (object en deelobject)
Kardinaliteit nu: optioneel in combinatie met Mogelijk geen waarde=ja.
Aanpassen naar: optioneel [0..1] en Mogelijk geen waarde is default (nee).

3.2.3.27 verwachteBouwhistWaarde (nieuw veld, invoegen na Beschrijving)
Naam: verwachteBouwhistWaarde : Boolean
Definitie: Een signalering voor de mogelijke aanwezigheid van bouwhistorische waarden 
Toelichting: Het aantonen van de verwachte bouwhistorische waarde vereist nader onderzoek of toegang. Bij niet aantreffen wordt de waarde nee.
Kardinaliteit: optioneel [0..1] en Mogelijk geen waarde is default (nee).
Indicatie formele historie: ja

3.2.3.nn fysischLandschap (nieuw veld)
Naam: fysischLandschap : Fysiologie
Definitie: 
Toelichting: combineren met Type is 'gebied'
Kardinaliteit: optioneel [0..1] en Mogelijk geen waarde is default (nee).
Indicatie formele historie: ja

3.2.3.nn cultuurLandschap (nieuw veld)
Naam: cultuurLandschap : Cultuur
Definitie: 
Toelichting: combineren met Type is 'gebied'
Kardinaliteit: optioneel [0..1] en Mogelijk geen waarde is default (nee).
Indicatie formele historie: ja

3.2.3.nn toelichtingLandschap (nieuw veld)
Naam: cultuurLandschap : Cultuur
Definitie: 
Kardinaliteit: optioneel [0..1] en Mogelijk geen waarde is default (nee).
Indicatie formele historie: ja

**Comment by rcdeboer** [comment]
Er zijn verwijzingen naar 2 (nog niet-bestaande) codelijsten geïntroduceerd, die nog moeten worden opgesteld en toegevoegd aan de codelijsten in deze git-repo. Het gaat om fysiologie.xlsx en cultuur.xlsx.

Het type 'Cultuur' bij toelichtingLandschap lijkt onjuist. Ik heb daar nu een CharacterString van gemaakt.

**Comment by marjoleinsteeman** [comment]
De volgende punten kunnen worden bijgewerkt:

attribuutsoort **fysischLandschap** : Fysiologie
definitie: Categorisering van landschap naar ontstaan van fysisch geografische eigenschappen zoals reliëf en grondsoort, waarop de nu nog herkenbare ontginning in het verleden plaatsvond.
toelichting: Het typeren van fysische geografie vindt plaats in combinatie met het beschrijven van het cultuurlandschap. Dit gebeurt in principe voor gebieden (of eventueel terreinen). De gebieden (en terreinen) vormen een landsdekkend geheel.

**Fysiologie** wordt geen codelijst, maar een enumeratie, met de volgende definitie:
Typologie van fysisch geografische eigenschappen zoals reliëf en grondsoort.
Waarden:
lösslandschappen |L| landschap met lössafzetting
stuwwallandschappen |S| heuvels in het landschap die ontstaan zijn doordat een gletsjer de grond heeft opgeduwd
dekzandlandschappen |D| landschap met zandafzetting uit de laatste ijstijd; dekzanddekens en -ruggen
keileemlandschappen |K| landschap met stenen en door het ijs fijngemalen sediment dat achterblijft na het smelten van het landijs
plateaulandschappen |P| betrekkelijk vlak landschap, relatief hoog gelegen, dat geheel of vrijwel geheel begrensd wordt door steil aflopende terreinen
rivierlandschappen |R| landschap waar de rivieren vroeger vrij doorheen stroomden; hieronder ook oeverwallen en kommen
rivierterraslandschappen |T| landschap dat als restant van een vroegere riviervlakte is ontstaan, toen een rivier op een hoger niveau in het landschap stroomde
veenlandschappen |V| landschap met oorspronkelijk een laag veengrond
zeekleilandschappen |Z| landschap met afzettingslagen van zand en klei (slib) uit zee
duinlandschappen |U| duinen en strand, gevormd door zeestromingen en de wind
water |W| gebied waar het landschap grotendeels onder water stond (of staat)

Toevoegen attribuutsoort **fysischDeelLandschap** (term uit codelijst SubFysiologie)
Herkomst | ERS
Definitie |  Nadere onderverdeling fysischLandschap.
Herkomst definitie | ERS
Toelichting | Fysisch geografische specificatie binnen een fysischLandschap, te gebruiken al naar gelang de schaal en cultuurhistorisch belang. Kan alleen worden gebruikt in combinatie met het veld fysischLandschap.
Datum opname | 20191001
Indicatie formele historie | Ja
Kardinaliteit | 0..1
Authentiek | Overig

attribuutsoort **ontginning** (term uit codelijst Ontginning)
definitie: Categorisering van gebieden naar de wijze waarop deze door mensen in cultuur zijn gebracht (of waar dat is uitgebleven).
toelichting: Het ontginningstype is een overkoepelend niveau van cultuurlandschappen. Het typeren van het historische ontginning- en cultuurlandschap vindt plaats in combinatie met het beschrijven van de fysische geografie. Dit gebeurt in principe voor gebieden (of eventueel terreinen). De gebieden (en terreinen) vormen een landsdekkend geheel.

attribuutsoort toelichtingLandschap wijzigen in **cultuurlandschap** (term uit codelijst Cultuurlandschap)
Herkomst | ERS
Definitie | Nadere onderverdeling binnen een ontginningstype.
Herkomst definitie | ERS
Toelichting | Specificatie van een gebied of terrein, aan de hand van landschappelijke kenmerken (reliëf, begroeiing, openheid, verkaveling, leeftijd enz). Cultuurlandschappen zijn vaak gerelateerd aan één ontginningstype.
Datum opname | 20191001
Indicatie formele historie | Ja
Kardinaliteit | 0..1
Authentiek | Overig

codelijst Fysiologie wordt een enumeratie (zie boven)

toevoegen: codelijst **SubFysiologie**
definitie: Fysische geografische kenmerken die de kwalificatie fysischLandschap nader specificeren.
toelichting: In sommige gevallen volstaat de kwalificatie fysischLandschap niet en dient deze nader te worden gespecificeerd.

toevoegen: codelijst **Ontginning**
definitie: Typologie van de wijze waarop het landschap in cultuur is gebracht.
toelichting: Naar verwachting is de verzameling Ontginningstypen eindig. Te zijner tijd zal de codelijst kunnen worden omgezet naar een enumeratie. Op dit moment is de codelijst nog niet volledig voor heel Nederland.

codelijst Cultuur wijzigen in **Cultuurlandschap**
definitie: Kenmerken van het landschap die een nadere indeling van het toegepast ontginningstype geven.
toelichting: De codelijst zal naar verwachting langer worden naarmate meer Ontginningen worden opgenomen.

**Comment by marjoleinsteeman** [comment]
De definitie/toelichting van de codelijst **Ontginning** is fout (dubbelt met SubFysiologie); dit moet zijn:
definitie: Typologie van de wijze waarop het landschap in cultuur is gebracht.
toelichting: Naar verwachting is de verzameling Ontginningstypen eindig. Te zijner tijd zal de codelijst kunnen worden omgezet naar een enumeratie. Op dit moment is de codelijst nog niet volledig voor heel Nederland.

De definitie van de codelijst **Cultuurlandschap**:
Graag "het toegepast ontginningstype..." wijzigen in "de aanwezige ontginning...".

Kunnen we de volgorde van ontginning en cultuurlandschap omdraaien? 

De naam van de **codelijst voor ontginning** is gewijzigd; de verwijslink moet daardoor worden aangepast (ontginning.xlsx)
De codelijst voor subfysiologie is geupload.

Tenslotte: graag alle 'landschappen' in de **enumeratie van Fysiologie** wijzigen in 'landschap'. Dus naar enkelvoud omzetten. Sorry hier voor de verwarring.

**Comment by marjoleinsteeman** [comment]
Laatste puntje: de volgorde van ontginning en cultuurlandschap in de attributenlijst van ErfgoedObject is nog niet gewijzigd. Zou je die nog kunnen omkeren?

De codelijsten Ontginning en Cultuurlandschap kunnen de laatste paragrafen worden: 5.5 en 5.6. Dan is het helemaal in lijn.
