### ISSUE TITLE
samenvatting failed

### ISSUE THREAD

**Issue by marjoleinsteeman** [ErfgoedRegistratieStandaard/ers-spec#11]
De import van de samenvatting in het document failed.

**Comment by rcdeboer** [comment]
Hij raakte in de war van de spaties die aan het begin van de regel stonden bij de bullet list. Ik heb dat deel aangepast (4ba60f2ecaa35aff7c7190410e38baead9cf19e6) en de samenvatting wordt nu weer goed ingeladen.
