### ISSUE TITLE
attribuutsoorten omgeving

### ISSUE THREAD

**Issue by marjoleinsteeman** [ErfgoedRegistratieStandaard/ers-spec#16]
**type**
definitie: indeling van omgeving naar de ruimtelijke betekenis van de omgeving voor het ErfgoedObject
toelichting: de ruimtelijke betekenis van de omgeving voor een ErfgoedObject kan van belang zijn voor de bescherming en daarmee voor de regels of de toepassing van regels die deze bescherming moeten bewerkstelligen. Het type bepaalt ook of de ErfgoedOmgeving een eigen contour heeft.

**contour**
definitie: de tweedimensionale geometrische representatie van het vlak dat wordt gevormd door de omtrekken van een ErfgoedOmgeving.
toelichting: Een samengesteld geometriegegevenstype waarbij wordt afgedwongen dat voor de geometrie een keuze gemaakt moet worden tussen een vlak (Polygon) of een multivlak (MultiPolygon), conform ISO/IEC 13249-3:2016. Deze standaard beschrijft de vastlegging in WKT-formaat.
Alleen geometrieën die voldoen aan het Simple Features profile conform ISO 19125-1:2004 zijn toegestaan.
Het toegepaste coördinatenstelsel is dat van de Rijksdriehoeksmeting (RD-stelsel). De coördinaten zijn op de millimeter nauwkeurig en de eenheid is meter. Elk coördinaat heeft maximaal drie decimalen. Zo nodig wordt daarvoor afgerond. Wanneer de bron voor een geometrie beperkt is tot een punt of een lijn, kan deze als vlak worden geregistreerd door een buffer toe te voegen. Daarbij wordt de breedte van de buffer geschat.
De aanwezigheid van een contour is afhankelijk van het type. Wanneer type=complex, dan heeft het OmgevingsObject geen eigen contour. Bij de overige types heeft het OmgevingsObject in principe wel een contour. 
kardinaliteit: [0..1]

**naam**
definitie: Naam waaronder het OmgevingsObject bekend staat
toelichting: De naam van een complex kan overeenkomen met de naam van een van de samenstellende ErfgoedObjecten. Ten behoeve van de registratie kan een naam worden toegekend of van het ErfgoedObject herhaald.
authentiek: nee
kardinaliteit: [0..1]

**beschrijving**
definitie: Beschrijving van de aard, verschijningsvorm, bron of oorsprong en eventueel beoogde bescherming van het OmgevingsObject.
toelichting: naar keuze in te vullen vrije tekst.
authentiek: nee

**Comment by rcdeboer** [comment]
Authentiek=nee is geen geldige waarde in MIM. Daarvoor wordt Authentiek=Overig voorgeschreven. Cf. https://docs.geostandaarden.nl/mim/mim/#authentieke-gegevens
