### ISSUE TITLE
Attribuutsoort "aanwezig" onvolledig

### ISSUE THREAD

**Issue by joerivanes** [ErfgoedRegistratieStandaard/ers-spec#23]
https://erfgoedregistratiestandaard.github.io/ers-spec/#aanwezig-0 

Attribuutsoort heeft geen definitie/ andere metagegevens.

**Comment by marjoleinsteeman** [comment]
Wanneer ik via de link in dit issue spring kom ik op een incomplete versie van de standaard. Daarin ontbreekt idd bij aanwezig de definitie etc. Zowel bij object als deelobject.
Als ik via de link op de Codepagina (onderaan) spring, kom ik wel op de complete versie. Hier is deze eigenschap wel gevuld met metadata.
