### ISSUE TITLE
Vastlegging van ruimtelijke attributen

### ISSUE THREAD

**Issue by joerivanes** [ErfgoedRegistratieStandaard/ers-spec#24]
Waarom is bij ruimtelijke attribuutsoorten zoals "[Contour](https://erfgoedregistratiestandaard.github.io/ers-spec/#contour-1)" gekozen voor Datatype "string" als Datatype? Er wordt wel gezegd dat de aanpak van de BAG wordt gevolgd voor het vastleggen van een contour. De [BAG](https://www.geobasisregistraties.nl/documenten/publicatie/2018/03/12/catalogus-2018) volgt voor het vastleggen van geometrie het ISO 19107 Spatial Schema. Voor de uitwisseling van bestanden met deze geometrie wordt de Geography Markup Language (GML) versie 3.1.1 toegepast (Zie IMBAG 3.3). 

Ook mag er van ERS naar de BGT worden verwezen. Het informatiemodel achter de BGT is IMGeo. IMGeo hanteert het Basismodel Geo-Informatie (NEN 3610:2011) en CityGML 2.0 als uitgangspunt voor het vastleggen van geometrie. Aangezien naast NEN3610, dat uitgaat van de ISO19107 en GML, CityGML 2.0 wordt toegestaan, betekent dat het optioneel mogelijk is om 2.5D of 3D geometrieën toe te voegen aan IMGeo objecten. (Zie [IMGeo specificatie 2.5](https://docs.geostandaarden.nl/imgeo/catalogus/imgeo/#x3d-in-imgeo) )

Ondertussen zijn er nieuwere versies uit van zowel de ISO-19107 en GML, dus wanneer gebruikers de ERS willen gaan implementeren is het voor hun nu onduidelijk welke standaarden ze moeten toepassen. Zeker wanneer de IMBAG in de toekomst overstapt op de nieuwe versies van de geostandaarden. Geonovum benadrukt op [deze webpagina](https://www.geonovum.nl/geo-standaarden/geography-markup-language-gml) dat deze standaarden op de pas-toe-of-leg-uit-lijst van het Forum Standaardisatie zijn opgenomen. Om aan deze eis te voldoen wordt bij ieder Geonovum informatiemodel altijd een stukje over geometrie opgenomen (wat in het geval van de ERS een aangepaste versie van het stukje in de BAG-specificatie kan zijn). Daarnaast is het belangrijk om aan te geven wat voor soort geometrie we verwachten bij een attribuutsoort als "contour". Is dit een vlak, of bijcoorbeeld een multivlak? Is het object in 2D 2.5D of 3D? 3D objecten zouden kunnen voorkomen aangezien ook wordt Een stukje hierover toevoegen + specifiek ISO-19107 datatypen gebruiken in de ERS zou de toepassing van geometrie kunnen verduidelijken.

**Comment by rcdeboer** [comment]
Opvolging: paragraaf met toelichting over te hanteren geo-standaarden irt de datatypen in het model.

**Comment by joerivanes** [comment]
Zie: https://github.com/ErfgoedRegistratieStandaard/ers-spec/pull/27

**Comment by rcdeboer** [comment]
Merge van #27 uitgevoerd, daarmee is dit ticket afgerond.
