### ISSUE TITLE
API spec

### ISSUE THREAD

**Issue by marjoleinsteeman** [ErfgoedRegistratieStandaard/ers-spec#30]
In het API schema Waardekenmerken **kloppen een paar attributen niet**: themaCultuurhistorie, fysischLandschap, toelichtingLandschap. Moet worden:
fysischLandschap
fysischDeelLandschap
themaCultuurhistorie
ontginning
cultuurLandschap
Het staat ook bij ErfgoedObject-Full verkeerd, maar in de logica van de schema's zou dit slechts op 1 plek hoeven te worden gecorrigeerd.

De naamgeving van de schema's heeft een **liggend streepje**; dit geeft problemen bij het verwerken in code. Daarom verzoek om de schema's te hernoemen naar camelNose notatie: registratiekenmerkenErfgoedObject enz.
Voor de schema's Full en Minimal heb ik een alternatieve naam:
ErfgoedObject-Full wijzigen in erfgoedObject (Full dus weglaten)
ErfgoedObject-Minimal wijzigen in basisErfgoedObject
ErfgoedObjecten-Collectie wordt dan: collectieErfgoedObjecten
Tenslotte het voorstel om IM-ERS-Object te veranderen in: ERSObject. Dit zou ik ook graag in het informatiemodel aanpassen (zie elders).

Bij het **attribuut _links** wordt verwezen naar 'self' en 'next'. Dient hier ook het attribuut 'previous' te worden toegevoegd? Aangezien deze ook in vergelijkbare specs van de BAG voorkomt. Overigens is het nut van de 'self' niet duidelijk, vooral als je maar 1 id opvraagt. Is dit een verplicht veld?

**Comment by rcdeboer** [comment]
- Alle kenmerken zijn nagelopen en goedgezet.
-- Het gebruik van self komt voort uit Design Rule API-73 uit de Nederlandse API-strategie (https://docs.geostandaarden.nl/api/API-Strategie-ext/#api-73)
- Het gebruik van next komt voort uit Design Rule API-42 uit de Nederlandse API-strategie (https://docs.geostandaarden.nl/api/API-Strategie-ext/#api-42). In lijn met die design rule is 'prev' nu ook toegevoegd aan de ERS API-spec.

@marjoleinsteeman - Een liggend streepje is valide in de naam van een schema (zie https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.1.md#components-object). Welke softwarematige verwerking gaat hierop fout?

**Comment by marjoleinsteeman** [comment]
Naar ik heb begrepen: de software die Ferdinand gebruikt om de lokale variant van de API-specs te genereren uit onze database/toepassing. Koppeltekens in een veldnaam worden niet toegestaan.

Met de toegestane naamgeving komen we er niet echt uit. Wanneer ik [vergelijk met de BAG](https://lvbag.github.io/BAG-API/Technische%20specificatie/#/) worden daar alleen lage streepjes gebruikt, en alleen bij bepaalde suffixen (die bij ons niet voorkomen). 
Dus voorstel om het streepje weg te laten en alles aan elkaar te schrijven met behoud van de hoofdletters.
Ander bezwaar was het gebruik van het engels; dat doen we verder nergens, alleen hier met de term Full/Minimal.
Dit zou misschien kunnen worden opgelost met:
suffix -Full weglaten
suffix -Minimal vervangen door Basis

Excuus: ik heb de volgorde van de laatste items verkeerd doorgegeven. Zou moeten zijn:
themaCultuurhistorie
fysischLandschap
fysischDeelLandschap
ontginning
cultuurLandschap

Tenslotte zag ik dat bij de datumvelden in de registratiekenmerken van het ErfgoedObject nog een date-time specificatie wordt gebruikt; dat moet zijn date.
Nog niet alle velden hebben een voorbeeldwaarde; vullen jullie die nog in op basis van het [exceldocument](https://github.com/ErfgoedRegistratieStandaard/ers-spec/blob/main/documents/labelsERS_20230218.xlsx) op github?

**Comment by rcdeboer** [comment]
Datumvelden gaat om:
<html>
<body>


datumInProcedure | string($date-time)readOnly: trueminimum: 0maximum: 1Zie specificatie.
-- | --
datumAanwijzing | string($date-time)readOnly: trueminimum: 0maximum: 1Zie specificatie.
datumNietAanwijzen | string($date-time)readOnly: trueminimum: 0maximum: 1Zie specificatie.
datumAfvoeren | string($date-time)readOnly: trueminimum: 0maximum: 1Zie specificatie.


</body>
</html>datumInProcedure	string($date-time)
readOnly: true
minimum: 0
maximum: 1
Zie [specificatie](https://erfgoedregistratiestandaard.github.io/ers-spec/#datuminprocedure).

datumAanwijzing	string($date-time)
readOnly: true
minimum: 0
maximum: 1
Zie [specificatie](https://erfgoedregistratiestandaard.github.io/ers-spec/#datumaanwijzing).

datumNietAanwijzen	string($date-time)
readOnly: true
minimum: 0
maximum: 1
Zie [specificatie](https://erfgoedregistratiestandaard.github.io/ers-spec/#datumnietaanwijzen).

datumAfvoeren	string($date-time)
readOnly: true
minimum: 0
maximum: 1
Zie [specificatie](https://erfgoedregistratiestandaard.github.io/ers-spec/#datumafvoeren).
