### ISSUE TITLE
Logica schemas API

### ISSUE THREAD

**Issue by marjoleinsteeman** [ErfgoedRegistratieStandaard/ers-spec#32]
In de logica van de schema's kan telkens worden **verwezen naar andere schema's**; dit maakt de samenhang tussen de schema's goed duidelijk. Zie bijvoorbeeld ErfgoedObjecten-Collectie waarbij gebruik wordt gemaakt van ErfgoedObject-Minimal

Op een paar punten lijkt dit nog niet helemaal in orde. Bijvoorbeeld: bij ErfgoedObject-Minimal moet verwezen worden naar IM-ERS-Object op een manier dat je die kunt 'openklappen'. Dan zie je ook welke velden in het schema Minimal aan het IM-ERS-Object toevoegt. Dat zie je nu niet.
Het lijkt erop dat dit nog niet af is. Ik zou verwachten dat de ErfgoedObject-Minimal wordt opgebouwd uit:
IM_ERS-Object
Registratiekenmerken-ErfgoedObject
Locatiekenmerken-ErfgoedObject

Voor ErfgoedObject-Full hebben we een keuze. 
Optie1: verwijzen naar Minimal en Waardekenmerken. 
Optie2: verwijzen naar:
IM_ERS-Object
Registratiekenmerken-ErfgoedObject
Locatiekenmerken-ErfgoedObject
Waardekenmerken-ErfgoedObject
Voor beide valt wat te zeggen.

De **Extension** staat nu apart gedefinieerd, met een paar kenmerken die we kennen uit de huidige implementatie. Ik neem aan dat deze in de definitieve versie niet zo worden opgenomen; de extensie is een lege huls die je kunt gebruiken in een lokale variant. Is het dan ook niet zinvol om de extensie op te nemen in de Minimal en Full varianten? Met andere woorden: dat je vooraf specificeert waar de extensie-kenmerken kunnen worden toegevoegd?

**Comment by rcdeboer** [comment]
- Het verwijzen naar andere schema's zorgt dat de inhoud van dat schema in zijn geheel in het verwijzende schema wordt geplaatst. De opbouw van ErfgoedObject-Minimal en ErfgoedObject-Full volgt precies de structuur zoals hierboven uitgewerkt, waarbij voor ErfgoedObject-Full 'Optie 1' wordt gevolgd.
```javascript
ErfgoedObject-Minimal:
  allOf:
    - $ref: '#/components/schemas/IM-ERS-Object'
    - $ref: '#/components/schemas/Registratiekenmerken-ErfgoedObject'
    - $ref: '#/components/schemas/Locatiekenmerken-ErfgoedObject'
ErfgoedObject-Full:
  allOf:
    - $ref: '#/components/schemas/ErfgoedObject-Minimal'
    - $ref: '#/components/schemas/Waardekenmerken-ErfgoedObject'
    - $ref: '#/components/schemas/ErfgoedObject-Situering'
    - $ref: '#/components/schemas/ErfgoedObject-Extension'
```
- In de ErfgoedObjecten-Collectie is de situatie iets anders, omdat ErfgoedObjecten-Collectie niet bestaat uit (alle eigenschappen van) een ErfgoedObject-Minimal, maar een *lijst* (array) bevat, genaamd 'items', die 0 of meer (minimal) erfgoedobjecten bevat. Je klapt in deze collectie dus niet het 'ErfgoedObject-Minimal' uit, maar de array 'items' waarin elementen zitten die het schema 'ErfgoedObject-Minimal' volgen.
```javascript
items:
  type: array
  items:
    $ref: '#/components/schemas/ErfgoedObject-Minimal'
  readOnly: true
``` 
- In de definitieve versie is het Extensie-blok inderdaad leeg, en kan de huidige versie daarnaast als voorbeeld worden gebruikt hoe je de standaard kan uitbreiden met een lokale extensie. Het uitgangspunt is dat de extensie alleen bij de 'Full' versie van het object wordt teruggegeven. Dit houdt de structuur en werking van de extensie overzichtelijk. Als er een goede use case is om ook bij het Minimal object een extensie op te nemen, kan dat prima in de specificatie worden verwerkt. Het maakt de structuur van de extensieblokken dan wel ingewikkelder (een Full-extensie gekoppeld aan een Full-object dat ook de Minimal-extensie omvat die aan het Minimal-object is gekoppeld).

**Comment by marjoleinsteeman** [comment]
Ik begrijp het, dank.
Check: soms staat er een 'description', namelijk bij de -Full en -Minimal schema's.
Moet deze nog worden uitgewerkt?
Moet deze ook aan de andere schema's worden toegevoegd?
Ik zou verwachten dat hierin iets staat over de samenstelling van de schema's (samenvoegen van verschillende kenmerken). Omdat je dat verder nergens kan zien. Of is dat een verkeerde gedachte?

Wat betreft de extension:
In het voorbeeld waarbij adresinformatie wordt meegegeven is het logischer om de extensie onder te brengen bij situering; dan kun je per adresid (betreftAdres) de bijbehorende adresgegevens vermelden.
Een usecase voor de Minimal variant is er wel: juist bij het ophalen van de basis is het fijn als we een samenvatting van de adressen kunnen meegeven. In de huidige applicatie is er zo'n veld; dat heet 'Adressering'.
Tenslotte hadden we in de onze api de mogelijkheid om een link naar fotos of documenten mee te geven. Dat zou een toevoeging aan de Full zijn.

Tenslotte: we hebben het meerdere keren gehad over de opbouw van de identificatie. Ik dacht dat we hadden besloten dit als 1 veld te beschrijven, maar dat er in de praktijk wel een splitsing kan zijn tussen de (standaard) namespace en het unieke nummer. Hoe gaan we daar nu mee om in de API? Kunnen we hier volstaan met het unieke nummer, op één of andere manier??

**Comment by rcdeboer** [comment]
(1) description is nu de beschrijving van het laatst 'toegevoegde' schema. Dat is verwarrend. Het liefst een beschrijving BIJ het desbetreffende schema (dus een specifieke beschrijving voor de extensie, een specifieke beschrijving voor het ErfgoedObject, en een specifieke beschrijving voor het IM-ERS-object). Als dat technisch niet lukt, beschrijvingen leeg laten.

(2) extensieblokken voor alle schema's introduceren (dus ook voor Situering). Ook voor de Minimal-blokken.

(3) de tekst bij 'identifier' moet duidelijker maken dat het alleen de lokaalID betreft, en niet de namespace en/of versienummer. Ook aan de hand van een voorbeeld. Attribuut ook hernoemen naar lokaalID.
