### ISSUE TITLE
feedback op Specs standaard

### ISSUE THREAD

**Issue by marjoleinsteeman** [ErfgoedRegistratieStandaard/ers-spec#33]
**Een paar puntjes op de i.**

In de plaatjes van het informatiemodel staat nog "enumeration,Enumeratie"; dit graag wijzigen in Enumeratie.

In de plaatjes van het informatiemodel staat het type veld (of een verwijzing naar betreffende enumeratie of codelijst). Is er ergens een specificatie van deze types beschikbaar? Bijvoorbeeld: het type Year. Welke eisen moet dit aan voldoen?
Het viel mij op dat deze typen niet terugkomen in de specificatie van de API. Daar is beginJaar een string. Bij tijdstipRegistratie zie ik staan: string($date-time). Hoe verhouden de twee specs zich tot elkaar met betrekking tot deze veldtypes?

Het type veld van **monumentnummer** staat genoteerd als integer. Dit moet zijn string. In de definitie staat (correct) dat het een nummer of een code kan zijn. Dit geldt ook voor het **grondslag**: moet ook type veld string krijgen.

Het objecttype **IM_ERS_Object** hebben we toegevoegd om de gemeenschappelijke notatie van de identificatie uit te werken. Ik zou graag de naam van het objecttype wijzigen in ERSObject. Daarmee het gebruik van _ vermijden. En de prefix IM weglaten; deze voegt eigenlijk niets toe, denk ik. Zou dit nog gewijzigd kunnen worden?

Bij de enumeratielijsten is Code alleen bij Fysiologie van toepassing. Is het mogelijk om deze alleen daar te tonen?
Is het toevoegen van definities per enumeratiewaarde verplicht? Dan moeten we dat nog aanvullen. Zoniet dan graag weglaten waar leeg. :)

Het veld "aanwezig" staat als verplicht veld genoteerd, met 'mag leeg zijn'. Ik kan mijn eerdere aantekeningen hierover niet vinden, maar zou dit nog gewijzigd kunnen worden in [0..1] ? Het is typisch een veld dat normaal leeg wordt gelaten en alleen wordt gevuld om een bijzondere situatie te duiden.

Bij het attribuutsoort **ErfgoedObject.type** in de definitie 'Dit veld is verplicht' schrappen; dit blijkt voldoende uit het informatiemodel en is niet consequent overal vermeld. Het *tweede deel* van de toelichting graag wijzigen als volgt:
Nota Bene: een ErfgoedObject behoort tot één objectType. Bij een object met een mengvorm aan types moet een leidend type worden gekozen. Bijvoorbeeld een pand met een aangebouwde poort kan als één object worden vastgelegd, met type pand(en). Een begraafplaats met een baarhuisje wordt geregistreerd als terrein. 

De definitie bij attribuutsoort **ErfgoedDeelobject.type** graag wijzigen in: "Typering van de fysieke verschijningsvorm van het deelobject." De toelichting graag wijzigen als volgt: "Het ErfgoedDeelobject kent enkele aanvullende types (interieur, constructie, aanleg) ten opzichte van het ErfgoedObject. Anderzijds is het type gebied hier niet van toepassing."

De definitie van **ErfgoedDeelobject** is nog niet op orde (3.4.1).
Definitie: Een ErfgoedDeelobject beschrijft een onderdeel van een ErfgoedObject en overerft de aardRegistratie en bescherming van het ErfgoedObject.
Toelichting: Een ErfgoedDeelobject kan alleen bestaan in relatie tot één ErfgoedObject. De bescherming is per definitie gelijk aan het ErfgoedObject. De contour van het ErfgoedDeelobject kan zich binnen of buiten de contour van het ErfgoedObject bevinden. Het ErfgoedDeelobject kan daarmee een aanvulling zijn op de locatiekenmerken van het ErfgoedObject.

**Comment by rcdeboer** [comment]
- bij beginjaar, eindjaar patroon (4 cijfers 1-9) specificeren
- lokaalID: 16 cijfers 0-9

Datatypes toevoegen (waar mogelijk met verwijzing naar MIM)

Code en Definitie als tabelkolom weglaten als er geen enkele waarde voor is in die tabel.

**Comment by rcdeboer** [comment]
Oplossing voor dit ticket volgt. Aanpassing van het exportscript vergt nog wat tijd.

**Comment by rcdeboer** [comment]
Alle bovenstaande punten zijn verwerkt, m.u.v.
>In de plaatjes van het informatiemodel staat nog "enumeration,Enumeratie"; dit graag wijzigen in Enumeratie.
Dit is niet te wijzigen en heeft te maken met de wijze waarop Enterprise Architect de enumeratie technisch implementeert, nl. als class met stereotype 'enumeration', in combinatie met de stereotypering 'Enumeratie' conform MIM. Dat verklaart waarom er 2 stereotypes in de afbeelding getoond worden.

**Comment by marjoleinsteeman** [comment]
Alles nagelopen :)
